[servidor]
servidor = geo.cuartazona.es
usuario = cuartazona
contrasena = DQPF8eTUES6NF3aKQXyv1wqNRqcUmF2ECTXUKCwae4I
ruta_BBDD = /home/cuartazona/redes/
BBDD = redes.sqlite
ruta_fotos = /home/cuartazona/redes/app/static_p/fotos/
otros_archivos = log.txt,error.log
[local]
ruta_local = ./app/static_p/fotos/
