[configuracion]
telefono = 881 959 045
ruta_app = app/
clave_secreta = 043A0E8BCCC8A48E7B159ADA21C83053
cookie_secure = yes
cookie_samesite = Lax
cookie_httponly = yes
max_content_length = 3145728
duracion_sesion = 3600
